### ISSUE TITLE
Legacy v0.6.0 xpi?

### ISSUE THREAD

**Issue by letmeindude** [blackwinter/keyword-expansion#1]
Hi Jens,

I can't find legacy xpi (v0.6.0 and v0.3.0) on your site and unfortunately I don't have the skills to make one from your source files (zipping and renaming .zip to .xpi doesn't work).

I use [Pale Moon](https://www.palemoon.org/releasenotes.shtml), so v0.6.0 or v0.3.0 should work. I hope you will consider making available these legacy files.

Thank you.

**Comment by blackwinter** [comment]
Hey, thanks for your interest. I've uploaded a new legacy version ([v0.6.1](http://blackwinter.de/addons/keyword-expansion-legacy.xpi)), I hope that works for you. Please note that one can't sign legacy addons anymore and that support for this will be minimal.

**Comment by letmeindude** [comment]
Wow, thank you very much. It works on Pale Moon and no need for signing.

Forgive me if this is a silly question, but if I want Keyword Expansion (Legacy) to use the Clipboard instead of selected text would this mean complete extension rewrite or is it enough to replace some code here and there? For example:
selection = require("sdk/selection"); with selection = require("sdk/clipboard???");

This way I can make it browser independent, i.e. copy some text from my notes manager.
I guess (with clipboard) middle mouse click on a bookmark folder full of these "search bookmarks" would work and this way I can search multiple web sites with single click.

**Comment by letmeindude** [comment]
OMG, it works, IT WOOORKS. So happy it works.

I have replaced (in keyword-expansion.js):
"selection = require("sdk/selection");"   with   "clipboard = require("sdk/clipboard");"
and
"selection.text"   with   "clipboard.get()"

I don't know if you should close this issue or maybe keep it open for others to see, but once again thank you very much, your extension is a must have.

**Comment by Lootyhoof** [comment]
Please note - Pale Moon add-ons do not require signing.

If you are able to get this working as expected in Pale Moon (or [Basilisk](https://basilisk-browser.org/)), please consider publishing it on our [add-ons site](https://addons.palemoon.org/), using the [self-service panel](https://addons.palemoon.org/panel/). Before it can be accepted though, please be sure to add the following to the `engines` key of `package.json`, directly underneath the `firefox` entry:

```
"{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}": ">=27.1.0b1 <=28.*"
```
This will add support for Pale Moon within the install manifest, `install.rdf`, when the extension is built using `jpm`. Full details of how an example end result would look like can be found [here](https://developer.palemoon.org/Add-ons:Extensions/Jetpack), including documentation on how Pale Moon's SDK differs from Firefox's. If this is not added, the extension will be considered Basilisk-only and will only show on [that add-ons site](https://addons.basilisk-browser.org/) instead. With both application entries it would instead show on both sites.

Thanks!

**Comment by blackwinter** [comment]
@letmeindude: Unfortunately, I don't see myself installing another browser I don't know and/or use, just to test this change. If you'd like to submit a pull request (ideally supporting both methods), i'll happily merge it. If you'd also like to address Ryan's comment, feel free to do so (separately).

On the other hand, you can even fork the legacy branch and become its maintainer. That's totally fine by me; I'm *most probably* not going to return to it. With Pale Moon's add-ons site being as liberal as Ryan alludes to, you don't need my personal site for distribution. (I'm not opposed to giving you push access to this repository if that's what you prefer; but for this I'd like to get a better picture of you and your work first.)

Seeing as the originally reported issue has been resolved, I'm going to close this ticket. You can open new tickets/pull requests for additional issues if you still want to.
